swagger: "2.0"

schemes:
    - http
consumes:
    - application/json
produces:
    - application/json
info:
    description: Currency Conversion Project
    title: Currency Conversion Project
    version: 1.0.0

basePath: /api

components:
    securitySchemes:
        BearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT

paths:
    /login:
        post:
            tags:
                - Login
            parameters:
                - name: login
                  in: body
                  schema:
                      $ref: "#/definitions/login"
            responses:
                200:
                    description: Login
                    schema:
                        $ref: "#/definitions/login"
                default:
                    description: generic error response
                    schema:
                        $ref: "#/definitions/error"
    /user-wallet-accounts:
        get:
            tags:
                - User Wallet Accounts
            security:
                - BearerAuth: []   # Use OAuth with a different scope
            responses:
                200:
                    description: User Wallet Accounts
                    schema:
                        $ref: "#/definitions/user-wallet-accounts"
                401:
                    schema: 
                        $ref: '#/definitions/UnauthorizedError'
                default:
                    description: generic error response
                    schema:
                        $ref: "#/definitions/error"
    /create-exchage-offer:
        post:
            tags:
                - Create Exchange Offer
            parameters:
                - name: create-exchange-offer
                  in: body
                  schema:
                      $ref: "#/definitions/create-exchange-offer"
            responses:
                200:
                    description: Create Exchange Offer
                    schema:
                        $ref: "#/definitions/create-exchange-offer"
                default:
                    description: generic error response
                    schema:
                        $ref: "#/definitions/error"
    /send-offer:
        post:
            tags:
                - Send Offer
            parameters:
                - name: send-offer
                  in: body
                  schema:
                      $ref: "#/definitions/send-offer"
            responses:
                200:
                    description: Send Offer
                    schema:
                        $ref: "#/definitions/send-offer"
                default:
                    description: generic error response
                    schema:
                        $ref: "#/definitions/error"
definitions:
    login:
        type: object
        required:
            - email
            - password
        properties:
            email:
                type: string
                format: email
                minLength: 5
                maxLength: 255
            password:
                type: string
                format: password
                minLength: 5
                maxLength: 255
    user-wallet-accounts:
        type: object
    create-exchange-offer:
        type: object
        required:
            - base_currency
            - counter_currency
        properties:
            base_currency:
                type: string
                minLength: 3
                maxLength: 3
            counter_currency:
                type: string
                minLength: 3
                maxLength: 3
    send-offer:
        type: object
        required:
            - base_currency
            - counter_currency
        properties:
            base_currency:
                type: string
                minLength: 3
                maxLength: 3
            counter_currency:
                type: string
                minLength: 3
                maxLength: 3
    error:
        type: object
        properties:
            code:
                type: integer
                format: int64
            message:
                type: string
    UnauthorizedError:
        description: Access token is missing or invalid